import os

#Need to have Oracle TNS Names downloaded into the user/Oracle/network/admin directory
config_dir = os.path.join(os.path.expanduser("~"), "Oracle", "network", "admin")

ROOT_DIR = os.getcwd()
SFS_READ_USERNAME=os.environ.get("SFS_READ_USERNAME")
SFS_READ_PASSWORD=os.environ.get("SFS_READ_PASSWORD")

ADMISSIONS_READ_USERNAME=os.environ.get("ADMISSIONS_READ_USERNAME")
ADMISSIONS_READ_PASSWORD=os.environ.get("ADMISSIONS_READ_PASSWORD")

AIR_READ_USERNAME=os.environ.get("AIR_READ_USERNAME")
AIR_READ_PASSWORD=os.environ.get("AIR_READ_PASSWORD")

ALUMNI_READ_USERNAME=os.environ.get("ALUMNI_READ_USERNAME")
ALUMNI_READ_PASSWORD=os.environ.get("ALUMNI_READ_PASSWORD")

DW_READ_USERNAME=os.environ.get("DW_READ_USERNAME")
DW_READ_PASSWORD=os.environ.get("DW_READ_PASSWORD")

DPS_READ_USERNAME=os.environ.get("DPS_READ_USERNAME")
DPS_READ_PASSWORD=os.environ.get("DPS_READ_PASSWORD")

FINANCE_READ_USERNAME=os.environ.get("FINANCE_READ_USERNAME")
FINANCE_READ_PASSWORD=os.environ.get("FINANCE_READ_PASSWORD")

GENERAL_READ_USERNAME=os.environ.get("GENERAL_READ_USERNAME")
GENERAL_READ_PASSWORD=os.environ.get("GENERAL_READ_PASSWORD")

HR_READ_USERNAME=os.environ.get("HR_READ_USERNAME")
HR_READ_PASSWORD=os.environ.get("HR_READ_PASSWORD")

CCI_READ_USERNAME=os.environ.get("CCI_READ_USERNAME")
CCI_READ_PASSWORD=os.environ.get("CCI_READ_PASSWORD")

REGISTRAR_READ_USERNAME=os.environ.get("REGISTRAR_READ_USERNAME")
REGISTRAR_READ_PASSWORD=os.environ.get("REGISTRAR_READ_PASSWORD")

PNTR_HOST_NAME=os.environ.get("PNTR_HOST_NAME")
PNTR_EC_HOST_NAME=os.environ.get("PNTR_EC_HOST_NAME")
PNTR_BANNER_HOST_NAME=os.environ.get("PNTR_BANNER_HOST_NAME")
PPRD_EC_HOST_NAME=os.environ.get("PPRD_EC_HOST_NAME")
PPRD_BANNER_HOST_NAME=os.environ.get("PPRD_BANNER_HOST_NAME")
PRCT_BANNER_HOST_NAME=os.environ.get("PRCT_BANNER_HOST_NAME")
PRCT_HOST_NAME=os.environ.get("PRCT_HOST_NAME")
DEV_EC_HOST_NAME=os.environ.get("DEV_EC_HOST_NAME")
DEV_BANNER_HOST_NAME=os.environ.get("DEV_BANNER_HOST_NAME")
DEV_HOST_NAME=os.environ.get("DEV_HOST_NAME")