SELECT 
    GOREMAL_PIDM,
    GOREMAL_EMAL_CODE
FROM GENERAL.GOREMAL
WHERE GOREMAL_EMAL_CODE = 'MNET'
AND (GOREMAL_EMAIL_ADDRESS NOT LIKE '%@middlebury.edu'
AND GOREMAL_EMAIL_ADDRESS NOT LIKE '%@miis.edu')